# Generated by Django 3.0.7 on 2020-10-26 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="disliked",
            field=django_mysql.models.ListTextField(
                models.CharField(max_length=10, null=True), size=5
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="favored",
            field=django_mysql.models.ListTextField(
                models.CharField(max_length=10, null=True), size=5
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
