# Generated by Django 3.0.7 on 2020-11-01 14:48

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201101_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='classrooms',
            field=django_mysql.models.ListTextField(models.CharField(max_length=10, null=True), size=5),
        ),
    ]
