# Generated by Django 3.0.7 on 2020-11-01 14:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201101_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='classrooms',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='disliked',
            field=django_mysql.models.ListTextField(models.CharField(max_length=10, null=True), size=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favored',
            field=django_mysql.models.ListTextField(models.CharField(max_length=10, null=True), size=5),
        ),
    ]
