# Generated by Django 3.0.7 on 2020-11-01 14:57

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20201101_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="classrooms",
            field=django_mysql.models.ListTextField(
                models.CharField(max_length=10, null=True), default="", size=5
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="disliked",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="favored",
            field=models.CharField(max_length=200),
        ),
    ]
